"""Initial migration

Revision ID: 2797c9544355
Revises: 
Create Date: 2026-07-10 11:57:53.980118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2797c9544355'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('device_id', sa.String(), nullable=False),
    sa.Column('company_id', sa.String(), nullable=False),
    sa.Column('employee_id', sa.String(), nullable=True),
    sa.Column('collected_at', sa.DateTime(), nullable=False),
    sa.Column('agent_version', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_snapshots_collected_at'), 'snapshots', ['collected_at'], unique=False)
    op.create_index(op.f('ix_snapshots_company_id'), 'snapshots', ['company_id'], unique=False)
    op.create_index(op.f('ix_snapshots_device_id'), 'snapshots', ['device_id'], unique=False)
    op.create_table('battery_stats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('snapshot_id', sa.Integer(), nullable=False),
    sa.Column('battery_present', sa.Boolean(), nullable=True),
    sa.Column('charging_status', sa.String(), nullable=True),
    sa.Column('percentage', sa.Integer(), nullable=True),
    sa.Column('condition', sa.String(), nullable=True),
    sa.Column('cycle_count', sa.Integer(), nullable=True),
    sa.Column('full_charge_capacity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['snapshot_id'], ['snapshots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('snapshot_id')
    )
    op.create_table('compliance_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('snapshot_id', sa.Integer(), nullable=False),
    sa.Column('check_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['snapshot_id'], ['snapshots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compliance_results_check_id'), 'compliance_results', ['check_id'], unique=False)
    op.create_index(op.f('ix_compliance_results_snapshot_id'), 'compliance_results', ['snapshot_id'], unique=False)
    op.create_index(op.f('ix_compliance_results_status'), 'compliance_results', ['status'], unique=False)
    op.create_table('device_identities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('snapshot_id', sa.Integer(), nullable=False),
    sa.Column('serial_number', sa.String(), nullable=True),
    sa.Column('model_name', sa.String(), nullable=True),
    sa.Column('model_identifier', sa.String(), nullable=True),
    sa.Column('processor', sa.String(), nullable=True),
    sa.Column('hardware_uuid', sa.String(), nullable=True),
    sa.Column('total_memory', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['snapshot_id'], ['snapshots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('snapshot_id')
    )
    op.create_index(op.f('ix_device_identities_serial_number'), 'device_identities', ['serial_number'], unique=False)
    op.create_table('disk_volumes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('snapshot_id', sa.Integer(), nullable=False),
    sa.Column('volume_name', sa.String(), nullable=True),
    sa.Column('file_system', sa.String(), nullable=True),
    sa.Column('mount_point', sa.String(), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('available_bytes', sa.BigInteger(), nullable=True),
    sa.Column('encrypted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['snapshot_id'], ['snapshots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_disk_volumes_snapshot_id'), 'disk_volumes', ['snapshot_id'], unique=False)
    op.create_table('installed_software',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('snapshot_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('publisher', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['snapshot_id'], ['snapshots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_installed_software_name'), 'installed_software', ['name'], unique=False)
    op.create_index(op.f('ix_installed_software_snapshot_id'), 'installed_software', ['snapshot_id'], unique=False)
    op.create_table('memory_stats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('snapshot_id', sa.Integer(), nullable=False),
    sa.Column('ram_bytes', sa.BigInteger(), nullable=True),
    sa.Column('total_memory_bytes', sa.BigInteger(), nullable=True),
    sa.Column('used_memory_bytes', sa.BigInteger(), nullable=True),
    sa.Column('free_memory_bytes', sa.BigInteger(), nullable=True),
    sa.Column('page_size_bytes', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['snapshot_id'], ['snapshots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('snapshot_id')
    )
    op.create_table('network_interfaces',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('snapshot_id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('family', sa.String(), nullable=True),
    sa.Column('interface_name', sa.String(), nullable=True),
    sa.Column('internal', sa.Boolean(), nullable=True),
    sa.Column('mac', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['snapshot_id'], ['snapshots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_network_interfaces_snapshot_id'), 'network_interfaces', ['snapshot_id'], unique=False)
    op.create_table('os_info',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('snapshot_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(), nullable=True),
    sa.Column('product_name', sa.String(), nullable=True),
    sa.Column('product_version', sa.String(), nullable=True),
    sa.Column('build_version', sa.String(), nullable=True),
    sa.Column('architecture', sa.String(), nullable=True),
    sa.Column('kernel_name', sa.String(), nullable=True),
    sa.Column('kernel_release', sa.String(), nullable=True),
    sa.Column('hostname', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['snapshot_id'], ['snapshots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('snapshot_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('os_info')
    op.drop_index(op.f('ix_network_interfaces_snapshot_id'), table_name='network_interfaces')
    op.drop_table('network_interfaces')
    op.drop_table('memory_stats')
    op.drop_index(op.f('ix_installed_software_snapshot_id'), table_name='installed_software')
    op.drop_index(op.f('ix_installed_software_name'), table_name='installed_software')
    op.drop_table('installed_software')
    op.drop_index(op.f('ix_disk_volumes_snapshot_id'), table_name='disk_volumes')
    op.drop_table('disk_volumes')
    op.drop_index(op.f('ix_device_identities_serial_number'), table_name='device_identities')
    op.drop_table('device_identities')
    op.drop_index(op.f('ix_compliance_results_status'), table_name='compliance_results')
    op.drop_index(op.f('ix_compliance_results_snapshot_id'), table_name='compliance_results')
    op.drop_index(op.f('ix_compliance_results_check_id'), table_name='compliance_results')
    op.drop_table('compliance_results')
    op.drop_table('battery_stats')
    op.drop_index(op.f('ix_snapshots_device_id'), table_name='snapshots')
    op.drop_index(op.f('ix_snapshots_company_id'), table_name='snapshots')
    op.drop_index(op.f('ix_snapshots_collected_at'), table_name='snapshots')
    op.drop_table('snapshots')
    # ### end Alembic commands ###
